collections_config:
  pages:
    _enabled_editors:
      - visual
  posts:
    _enabled_editors:
      - content
      - visual

_inputs:
  content:
    type: markdown
  featured_image:
    type: image
    comment: Set your pages featured image here. This is used in metadata when sharing your website.
  body:
    type: textarea
  cta_button:
    type: select
    options:
      values:
        - Tour
        - Reserve
